services:
  docker-test-db:
    build: ./db
    ports:
      - 1433:1433
    networks:
      - app-net

  docker-test-web:
    build: ./
    ports:
      - 8080:80
    depends_on:
      - docker-test-db
    networks:
      - app-net

networks:
  app-net:
